sudo: required
services:
  - docker

script:
  - docker build -t io89/packages-client ./src/client
  - docker build -t io89/packages-nginx ./nginx
  - docker build -t io89/packages-server ./
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push those images to DockerHub
  - docker push io89/packages-client
  - docker push io89/packages-nginx
  - docker push io89/packages-server