version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    volumes:
      - /packages/backend/node_modules
      - ./:/packages/backend
  client:
    build:
      context: src/client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /packages/frontend/node_modules
      - ./src/client/:/packages/frontend
  ngnix:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '8080:80'