version: '3.2'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - /packages/backend/node_modules
      - ./:/packages/backend

  frontend:
    build:
      context: src/client
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'

