version: '3.2'
services:
  ngnix:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    volumes:
      - /packages/backend/node_modules
      - ./:/packages/backend
  client:
    build:
      context: src/client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'

